//! MCP server that exposes the code graph as 15 rmcp tools over stdio.
//!
//! Phase 3.1 ships the scaffold: [`CodeGraphServer`] with all 15 tools wired
//! through `#[tool_router]` plus the `ServerInner` state struct that future
//! tasks will read from. Every tool handler currently returns
//! `McpError::internal_error("not yet implemented (Phase 3.X)", None)` —
//! Phase 3.4 fills in the eight P0 handlers and Phase 3.5 fills in the
//! remaining seven.
//!
//! ## Tool wire format
//!
//! Tool descriptions are copied byte-for-byte from the Go reference at
//! `internal/tools/tools.go` for 13 of the 15 tools. Two are updated for
//! the multi-language Rust port:
//!
//! - `analyze_codebase`: widened from "Index a C/C++ codebase…" to "Index a
//!   codebase (C/C++, Rust, Go, Python) and build the code graph. Must be
//!   called before any query tools."
//! - `search_symbols`: keeps the existing description but gains a `language`
//!   parameter ("Filter by source language: cpp, rust, go, or python").
//!
//! Phase 3.7 captures these strings as wire-format snapshots; any future
//! divergence triggers `cargo insta review`.

use std::path::PathBuf;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;

use codegraph_core::RootConfig;
use codegraph_graph::Graph;
use codegraph_lang::LanguageRegistry;
use parking_lot::RwLock as PlRwLock;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::CallToolResult;
use rmcp::{tool, tool_handler, tool_router, ErrorData as McpError, ServerHandler};
use schemars::JsonSchema;
use serde::Deserialize;
use tokio::sync::Mutex as TokioMutex;

/// Placeholder for the active filesystem watcher's handle. Phase 4 replaces
/// this with the real `notify-debouncer-full` handle plus the channel /
/// task that drains its events. The unit struct is enough today to satisfy
/// the `Option<WatchHandle>` shape the design pinned in
/// `Designs/RustRewrite/README.md`.
pub struct WatchHandle;

/// Shared state owned by the running MCP server.
///
/// Layout follows `Designs/RustRewrite/README.md` "State Management":
/// - [`Self::graph`] uses `parking_lot::RwLock` (the canonical lock type
///   re-exported from `codegraph-graph`); query handlers take a read lock
///   for the duration of the query and serialize the response.
/// - [`Self::index_lock`] uses `tokio::sync::Mutex` because
///   `analyze_codebase` is async and the lock guard must cross await
///   points. `try_lock` returns "indexing already in progress" matching
///   Go behavior.
/// - [`Self::indexed`] is an `AtomicBool` so [`CodeGraphServer::require_indexed`]
///   can check the flag with no lock acquisition.
pub struct ServerInner {
    /// In-memory code graph populated by `analyze_codebase`.
    pub graph: PlRwLock<Graph>,
    /// Plugin registry (one entry per registered language).
    pub registry: LanguageRegistry,
    /// `true` after at least one successful `analyze_codebase`. Read by
    /// [`CodeGraphServer::require_indexed`] without taking a lock.
    pub indexed: AtomicBool,
    /// Single-flight guard for `analyze_codebase`. `try_lock` returns
    /// "indexing already in progress" identical to the Go behavior; the
    /// watch loop's `reindex_file` (Phase 4) also acquires this lock to
    /// close the analyze-vs-watch merge race the Go implementation has.
    pub index_lock: TokioMutex<()>,
    /// Last indexed root directory; needed by `watch_start`.
    pub root_path: PlRwLock<Option<PathBuf>>,
    /// Active watcher, if any. Phase 4 fills [`WatchHandle`] in.
    pub watch: PlRwLock<Option<WatchHandle>>,
    /// Last-loaded `<root>/.code-graph.toml`. Defaults to
    /// [`RootConfig::default`] until `analyze_codebase` reads it from disk.
    pub config: PlRwLock<RootConfig>,
}

/// MCP server exposing the code graph through 15 tools.
///
/// Cloneable because rmcp's macro-generated dispatch table holds the server
/// by value (the `tool_router` field is a `ToolRouter<Self>` and dispatch
/// borrows `&self` from the cloned handle). All shared state lives behind
/// the `Arc<ServerInner>`, so cloning is cheap and lock-respecting.
#[derive(Clone)]
pub struct CodeGraphServer {
    pub inner: Arc<ServerInner>,
    /// Tool dispatch table. Generated by `#[tool_router]` and used by
    /// `#[tool_handler]` to wire `call_tool` / `list_tools`.
    tool_router: ToolRouter<Self>,
}

impl CodeGraphServer {
    /// Construct a fresh server. The graph starts empty; the registry is
    /// taken by value (the registry is `!Clone` and is moved in here once
    /// at startup).
    pub fn new(registry: LanguageRegistry) -> Self {
        Self {
            inner: Arc::new(ServerInner {
                graph: PlRwLock::new(Graph::new()),
                registry,
                indexed: AtomicBool::new(false),
                index_lock: TokioMutex::new(()),
                root_path: PlRwLock::new(None),
                watch: PlRwLock::new(None),
                config: PlRwLock::new(RootConfig::default()),
            }),
            tool_router: Self::tool_router(),
        }
    }

    /// Number of registered tools. Used by the smoke test to confirm the
    /// `#[tool_router]` macro produced 15 entries before any IO loop runs.
    pub fn tool_count(&self) -> usize {
        self.tool_router.list_all().len()
    }

    /// Returns an error matching the Go reference's exact wording when the
    /// server has not yet been indexed. The em-dash is U+2014 (not a
    /// hyphen-minus) — wire-format tests in Phase 3.7 lock the byte
    /// sequence in.
    pub fn require_indexed(&self) -> Result<(), McpError> {
        if !self
            .inner
            .indexed
            .load(std::sync::atomic::Ordering::Acquire)
        {
            return Err(McpError::internal_error(
                "no codebase indexed — call analyze_codebase first",
                None,
            ));
        }
        Ok(())
    }
}

// Argument structs ---------------------------------------------------------
//
// One struct per tool; `Parameters<T>` extracts `T` from the JSON-RPC
// request's `arguments` field. `Option<T>` fields mean "absent in the
// request"; required fields are `T` directly. Validation (e.g. "at least
// one of query/kind/namespace/language") is the handler's job — Phase 3.4
// adds it.

/// Empty parameter struct for tools that take no arguments
/// (`detect_cycles`, `watch_start`, `watch_stop`). The empty `{}` JSON
/// object deserializes into this without error.
#[derive(Debug, Default, Deserialize, JsonSchema)]
pub struct EmptyParams {}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct AnalyzeCodebaseArgs {
    /// Absolute path to the directory to index.
    #[schemars(description = "Absolute path to the directory to index")]
    pub path: String,
    /// Force full re-index, ignoring any cache.
    #[schemars(description = "Force full re-index, ignoring any cache (default false)")]
    #[serde(default)]
    pub force: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetFileSymbolsArgs {
    #[schemars(description = "Absolute path to the source file")]
    pub file: String,
    #[schemars(
        description = "Only return top-level symbols (no nested methods/types) (default false)"
    )]
    #[serde(default)]
    pub top_level_only: Option<bool>,
    #[schemars(description = "Omit signature, column, end_line for compact output (default true)")]
    #[serde(default)]
    pub brief: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SearchSymbolsArgs {
    #[schemars(description = "Substring or regex pattern to match symbol names")]
    #[serde(default)]
    pub query: Option<String>,
    #[schemars(
        description = "Filter by symbol kind: function, method, class, struct, enum, typedef"
    )]
    #[serde(default)]
    pub kind: Option<String>,
    #[schemars(
        description = "Filter by namespace (substring match, e.g., 'Nfs' matches 'Ark::Nfs::V4')"
    )]
    #[serde(default)]
    pub namespace: Option<String>,
    #[schemars(description = "Filter by source language: cpp, rust, go, or python")]
    #[serde(default)]
    pub language: Option<String>,
    #[schemars(description = "Maximum results to return (default 20)")]
    #[serde(default)]
    pub limit: Option<u32>,
    #[schemars(description = "Skip first N matches for pagination (default 0)")]
    #[serde(default)]
    pub offset: Option<u32>,
    #[schemars(description = "Omit signature, column, end_line (default true)")]
    #[serde(default)]
    pub brief: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetSymbolDetailArgs {
    #[schemars(
        description = "Symbol ID in format file:name as returned by get_file_symbols or search_symbols"
    )]
    pub symbol: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetSymbolSummaryArgs {
    #[schemars(description = "Optional absolute path: scope counts to a single file")]
    #[serde(default)]
    pub file: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetCallersArgs {
    #[schemars(description = "Symbol ID in format file:name")]
    pub symbol: String,
    #[schemars(description = "Maximum traversal depth (default 1)")]
    #[serde(default)]
    pub depth: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetCalleesArgs {
    #[schemars(description = "Symbol ID in format file:name")]
    pub symbol: String,
    #[schemars(description = "Maximum traversal depth (default 1)")]
    #[serde(default)]
    pub depth: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetDependenciesArgs {
    #[schemars(description = "Absolute path to the source file")]
    pub file: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetOrphansArgs {
    #[schemars(description = "Filter by symbol kind: function, method (default: all callables)")]
    #[serde(default)]
    pub kind: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetClassHierarchyArgs {
    #[schemars(description = "Class name to look up")]
    pub class: String,
    #[schemars(
        description = "Traversal depth for transitive inheritance (default 1 = direct only)"
    )]
    #[serde(default)]
    pub depth: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetCouplingArgs {
    #[schemars(description = "Absolute path to the source file")]
    pub file: String,
    #[schemars(description = "'outgoing' (default), 'incoming', or 'both'")]
    #[serde(default)]
    pub direction: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GenerateDiagramArgs {
    #[schemars(description = "Symbol ID to center the call graph on (format: file:name)")]
    #[serde(default)]
    pub symbol: Option<String>,
    #[schemars(description = "File path to center the dependency graph on")]
    #[serde(default)]
    pub file: Option<String>,
    #[schemars(description = "Class name to center the inheritance diagram on")]
    #[serde(default)]
    pub class: Option<String>,
    #[schemars(description = "BFS traversal depth (default 1)")]
    #[serde(default)]
    pub depth: Option<u32>,
    #[schemars(description = "Maximum nodes in diagram (default 30)")]
    #[serde(default)]
    pub max_nodes: Option<u32>,
    #[schemars(
        description = "Output format: 'edges' (default, minimal JSON) or 'mermaid' (Mermaid flowchart syntax)"
    )]
    #[serde(default)]
    pub format: Option<String>,
    #[schemars(
        description = "When format=mermaid, add CSS styling and center node highlighting (default false)"
    )]
    #[serde(default)]
    pub styled: Option<bool>,
}

// Tool router --------------------------------------------------------------

/// Stub error returned by every tool handler in Phase 3.1. The phase tag
/// in the message lets `tools/list` consumers see which task is on the
/// hook for filling in each handler.
fn not_yet_implemented(phase: &'static str) -> McpError {
    McpError::internal_error(format!("not yet implemented ({phase})"), None)
}

#[tool_router]
impl CodeGraphServer {
    // -- P0 (Phase 3.4) ----------------------------------------------------

    #[tool(
        description = "Index a codebase (C/C++, Rust, Go, Python) and build the code graph. Must be called before any query tools."
    )]
    async fn analyze_codebase(
        &self,
        Parameters(_args): Parameters<AnalyzeCodebaseArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(description = "List all symbols (functions, classes, etc.) defined in a file")]
    async fn get_file_symbols(
        &self,
        Parameters(_args): Parameters<GetFileSymbolsArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(
        description = "Search for symbols by name pattern across the indexed codebase. Returns paginated results. Default brief mode omits signatures for token efficiency."
    )]
    async fn search_symbols(
        &self,
        Parameters(_args): Parameters<SearchSymbolsArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(description = "Get full details for a symbol by its ID")]
    async fn get_symbol_detail(
        &self,
        Parameters(_args): Parameters<GetSymbolDetailArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(
        description = "Get symbol counts grouped by namespace and kind — useful for codebase orientation"
    )]
    async fn get_symbol_summary(
        &self,
        Parameters(_args): Parameters<GetSymbolSummaryArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(description = "Find functions that call the given symbol (upstream call chain)")]
    async fn get_callers(
        &self,
        Parameters(_args): Parameters<GetCallersArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(description = "Find functions called by the given symbol (downstream call chain)")]
    async fn get_callees(
        &self,
        Parameters(_args): Parameters<GetCalleesArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    #[tool(description = "List files included/imported by the given file")]
    async fn get_dependencies(
        &self,
        Parameters(_args): Parameters<GetDependenciesArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.4"))
    }

    // -- P1+P2 + watch (Phase 3.5) -----------------------------------------

    #[tool(description = "Detect circular include dependencies in the indexed codebase")]
    async fn detect_cycles(
        &self,
        Parameters(_args): Parameters<EmptyParams>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(description = "Find symbols with no incoming call edges (uncalled functions/methods)")]
    async fn get_orphans(
        &self,
        Parameters(_args): Parameters<GetOrphansArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(description = "Get the inheritance tree for a class (base classes and derived classes)")]
    async fn get_class_hierarchy(
        &self,
        Parameters(_args): Parameters<GetClassHierarchyArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(description = "Get cross-file dependency counts for a file")]
    async fn get_coupling(
        &self,
        Parameters(_args): Parameters<GetCouplingArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(
        description = "Generate a graph diagram: call graph (symbol), file dependencies (file), or inheritance tree (class). Returns edges as JSON by default, or Mermaid syntax when format=mermaid."
    )]
    async fn generate_diagram(
        &self,
        Parameters(_args): Parameters<GenerateDiagramArgs>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(
        description = "Start watching the indexed directory for file changes and auto-reindex modified files"
    )]
    async fn watch_start(
        &self,
        Parameters(_args): Parameters<EmptyParams>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }

    #[tool(description = "Stop watching for file changes")]
    async fn watch_stop(
        &self,
        Parameters(_args): Parameters<EmptyParams>,
    ) -> Result<CallToolResult, McpError> {
        Err(not_yet_implemented("Phase 3.5"))
    }
}

#[tool_handler]
impl ServerHandler for CodeGraphServer {}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_server() -> CodeGraphServer {
        CodeGraphServer::new(LanguageRegistry::new())
    }

    /// The Phase 3.1 acceptance gate: `tools/list` must surface exactly 15
    /// tools. If a future task adds or removes a `#[tool]`, this assertion
    /// is the first place a wire-format change shows up.
    #[test]
    fn tool_router_registers_fifteen_tools() {
        let server = empty_server();
        assert_eq!(
            server.tool_count(),
            15,
            "expected 15 registered tools, got {}",
            server.tool_count(),
        );
    }

    /// Confirms every expected tool name is present. Names are part of the
    /// MCP wire contract — a typo would silently break any agent dispatching
    /// by name.
    #[test]
    fn tool_router_contains_every_expected_name() {
        let server = empty_server();
        let names: std::collections::HashSet<_> = server
            .tool_router
            .list_all()
            .into_iter()
            .map(|t| t.name.to_string())
            .collect();
        for expected in [
            "analyze_codebase",
            "get_file_symbols",
            "search_symbols",
            "get_symbol_detail",
            "get_symbol_summary",
            "get_callers",
            "get_callees",
            "get_dependencies",
            "detect_cycles",
            "get_orphans",
            "get_class_hierarchy",
            "get_coupling",
            "generate_diagram",
            "watch_start",
            "watch_stop",
        ] {
            assert!(
                names.contains(expected),
                "tool {expected} missing from router; have {names:?}",
            );
        }
    }

    /// `require_indexed` must produce the exact Go error wording (em-dash
    /// U+2014, not a hyphen-minus). Snapshot tests in Phase 3.7 will lock
    /// the byte sequence in across all error paths.
    #[test]
    fn require_indexed_returns_exact_go_wording() {
        let server = empty_server();
        let err = server
            .require_indexed()
            .expect_err("fresh server must report not indexed");
        assert_eq!(
            err.message.as_ref(),
            "no codebase indexed — call analyze_codebase first",
        );
    }

    /// `require_indexed` returns Ok once the atomic flag is set.
    #[test]
    fn require_indexed_succeeds_after_indexed_flag_set() {
        let server = empty_server();
        server
            .inner
            .indexed
            .store(true, std::sync::atomic::Ordering::Release);
        server.require_indexed().expect("indexed flag must pass");
    }

    /// Each Phase 3.1 stub must surface the correct phase tag so tool
    /// consumers can see which task owns the missing implementation.
    #[tokio::test]
    async fn p0_handler_stub_reports_phase_3_4() {
        let server = empty_server();
        let err = server
            .analyze_codebase(Parameters(AnalyzeCodebaseArgs {
                path: "/tmp/anything".to_string(),
                force: None,
            }))
            .await
            .expect_err("Phase 3.1 must stub all P0 handlers");
        assert!(
            err.message.contains("Phase 3.4"),
            "P0 stub must mention Phase 3.4, got {:?}",
            err.message,
        );
    }

    /// Symmetrical assertion for the Phase 3.5 stub family.
    #[tokio::test]
    async fn p1_handler_stub_reports_phase_3_5() {
        let server = empty_server();
        let err = server
            .detect_cycles(Parameters(EmptyParams::default()))
            .await
            .expect_err("Phase 3.1 must stub all P1+P2+watch handlers");
        assert!(
            err.message.contains("Phase 3.5"),
            "P1 stub must mention Phase 3.5, got {:?}",
            err.message,
        );
    }
}
