//! Wire-format snapshots of every tool's `tools/list` entry.
//!
//! Phase 3.7 captures the descriptor returned by
//! `CodeGraphServer::tool_router().list_all()` for each of the 15 registered
//! tools. Each entry includes:
//!
//! - `name` — the tool name string used by `tools/call` dispatch.
//! - `description` — Phase 3.1 wording (13 are byte-identical to the Go
//!   reference; `analyze_codebase` carries the multi-language widening and
//!   `search_symbols` carries the language-filter rider).
//! - `inputSchema` — the JSON schema for the Args struct, generated by
//!   schemars.
//!
//! These snapshots are the wire-format-of-record. Future PRs that change
//! a description, add a parameter, or rename a field must explicitly accept
//! the new snapshot via `cargo insta review` so the wire-level impact is
//! visible at review time.

use code_graph_lang::LanguageRegistry;
use code_graph_tools::CodeGraphServer;
use rmcp::model::Tool;

/// Find a tool descriptor by name. Panics if the tool is missing — the
/// 15-tool count is locked in by `tool_router_registers_fifteen_tools`,
/// so a missing tool here means a regression.
fn tool_entry(name: &str) -> Tool {
    let server = CodeGraphServer::new(LanguageRegistry::new());
    server
        .tool_descriptors()
        .into_iter()
        .find(|t| t.name == name)
        .unwrap_or_else(|| panic!("tool {name} missing from router"))
}

// --- P0 (Phase 3.4) ------------------------------------------------------

#[test]
fn tools_list_analyze_codebase() {
    insta::assert_json_snapshot!(tool_entry("analyze_codebase"));
}

#[test]
fn tools_list_get_file_symbols() {
    insta::assert_json_snapshot!(tool_entry("get_file_symbols"));
}

#[test]
fn tools_list_search_symbols() {
    insta::assert_json_snapshot!(tool_entry("search_symbols"));
}

#[test]
fn tools_list_get_symbol_detail() {
    insta::assert_json_snapshot!(tool_entry("get_symbol_detail"));
}

#[test]
fn tools_list_get_symbol_summary() {
    insta::assert_json_snapshot!(tool_entry("get_symbol_summary"));
}

#[test]
fn tools_list_get_callers() {
    insta::assert_json_snapshot!(tool_entry("get_callers"));
}

#[test]
fn tools_list_get_callees() {
    insta::assert_json_snapshot!(tool_entry("get_callees"));
}

#[test]
fn tools_list_get_dependencies() {
    insta::assert_json_snapshot!(tool_entry("get_dependencies"));
}

// --- P1+P2 (Phase 3.5) ---------------------------------------------------

#[test]
fn tools_list_detect_cycles() {
    insta::assert_json_snapshot!(tool_entry("detect_cycles"));
}

#[test]
fn tools_list_get_orphans() {
    insta::assert_json_snapshot!(tool_entry("get_orphans"));
}

#[test]
fn tools_list_get_class_hierarchy() {
    insta::assert_json_snapshot!(tool_entry("get_class_hierarchy"));
}

#[test]
fn tools_list_get_coupling() {
    insta::assert_json_snapshot!(tool_entry("get_coupling"));
}

#[test]
fn tools_list_generate_diagram() {
    insta::assert_json_snapshot!(tool_entry("generate_diagram"));
}

// --- Watch stubs (Phase 3.5; replaced for real in Phase 4) ----------------

#[test]
fn tools_list_watch_start() {
    insta::assert_json_snapshot!(tool_entry("watch_start"));
}

#[test]
fn tools_list_watch_stop() {
    insta::assert_json_snapshot!(tool_entry("watch_stop"));
}
