//! Wire-format snapshots of every tool's `tools/list` entry.
//!
//! Captures the descriptor returned by
//! `CodeGraphServer::tool_router().list_all()` for each of the 19 registered
//! tools. Each entry includes:
//!
//! - `name` — the tool name string used by `tools/call` dispatch.
//! - `description` — the original 13 are byte-identical to the Go
//!   reference; `analyze_codebase` carries the multi-language widening and
//!   `search_symbols` carries the language-filter rider; the three
//!   Rust-only additions (`get_status`, `find_overrides`,
//!   `find_class_candidates`) have no Go counterpart.
//! - `inputSchema` — the JSON schema for the Args struct, generated by
//!   schemars.
//!
//! These snapshots are the wire-format-of-record. Future PRs that change
//! a description, add a parameter, or rename a field must explicitly accept
//! the new snapshot via `cargo insta review` so the wire-level impact is
//! visible at review time.

use code_graph_lang::LanguageRegistry;
use code_graph_tools::CodeGraphServer;
use rmcp::model::Tool;

/// Find a tool descriptor by name. Panics if the tool is missing — the
/// 19-tool count is locked in by `tool_router_registers_nineteen_tools`,
/// so a missing tool here means a regression.
fn tool_entry(name: &str) -> Tool {
    let server = CodeGraphServer::new(LanguageRegistry::new());
    server
        .tool_descriptors()
        .into_iter()
        .find(|t| t.name == name)
        .unwrap_or_else(|| panic!("tool {name} missing from router"))
}

// --- Indexing + core symbol / call / dependency query tools ----------------

#[test]
fn tools_list_analyze_codebase() {
    insta::assert_json_snapshot!(tool_entry("analyze_codebase"));
}

#[test]
fn tools_list_analyze_codebase_async() {
    insta::assert_json_snapshot!(tool_entry("analyze_codebase_async"));
}

#[test]
fn tools_list_get_file_symbols() {
    insta::assert_json_snapshot!(tool_entry("get_file_symbols"));
}

#[test]
fn tools_list_search_symbols() {
    insta::assert_json_snapshot!(tool_entry("search_symbols"));
}

#[test]
fn tools_list_get_symbol_detail() {
    insta::assert_json_snapshot!(tool_entry("get_symbol_detail"));
}

#[test]
fn tools_list_get_symbol_summary() {
    insta::assert_json_snapshot!(tool_entry("get_symbol_summary"));
}

#[test]
fn tools_list_get_callers() {
    insta::assert_json_snapshot!(tool_entry("get_callers"));
}

#[test]
fn tools_list_get_callees() {
    insta::assert_json_snapshot!(tool_entry("get_callees"));
}

#[test]
fn tools_list_get_dependencies() {
    insta::assert_json_snapshot!(tool_entry("get_dependencies"));
}

// --- Structural-analysis + visualization tools -----------------------------

#[test]
fn tools_list_detect_cycles() {
    insta::assert_json_snapshot!(tool_entry("detect_cycles"));
}

#[test]
fn tools_list_get_orphans() {
    insta::assert_json_snapshot!(tool_entry("get_orphans"));
}

#[test]
fn tools_list_get_class_hierarchy() {
    insta::assert_json_snapshot!(tool_entry("get_class_hierarchy"));
}

#[test]
fn tools_list_get_coupling() {
    insta::assert_json_snapshot!(tool_entry("get_coupling"));
}

#[test]
fn tools_list_generate_diagram() {
    insta::assert_json_snapshot!(tool_entry("generate_diagram"));
}

// --- Watch lifecycle tools (real schemas, not stubs) -----------------------

#[test]
fn tools_list_watch_start() {
    insta::assert_json_snapshot!(tool_entry("watch_start"));
}

#[test]
fn tools_list_watch_stop() {
    insta::assert_json_snapshot!(tool_entry("watch_stop"));
}

// --- Operational diagnostics ----------------------------------------------

#[test]
fn tools_list_get_status() {
    insta::assert_json_snapshot!(tool_entry("get_status"));
}

// --- Override navigation --------------------------------------------------

#[test]
fn tools_list_find_overrides() {
    insta::assert_json_snapshot!(tool_entry("find_overrides"));
}

// --- Class-name disambiguation --------------------------------------------

#[test]
fn tools_list_find_class_candidates() {
    insta::assert_json_snapshot!(tool_entry("find_class_candidates"));
}

// --- Load-bearing description-substring regressions ------------------------
//
// The tool description strings are production behavior — agents pattern-match
// on them. The snapshots above pin every byte; these targeted assertions name
// the specific contract clauses that future edits must keep present, so a
// well-intentioned rewrite cannot silently drop a load-bearing phrase while
// the snapshot is re-accepted.
//
// Coverage:
// - `get_callers` / `get_callees`: CallChain field semantics (`file` = call
//   SITE, `symbol_id` = DEFINITION site, divergence at depth ≥ 2),
//   resolved-only filter (parity with `generate_diagram`), and non-callable
//   soft-hint behavior (kind names + the alternative-tool routing).
// - `search_symbols`: `suggestions` field semantics (anchored `^…$` AND
//   `total == 0` trigger condition, `count_only` exclusion).

fn description_of(name: &str) -> String {
    let tool = tool_entry(name);
    tool.description
        .as_ref()
        .map(|d| d.to_string())
        .unwrap_or_default()
}

fn assert_contains(haystack: &str, needle: &str, tool: &str) {
    assert!(
        haystack.contains(needle),
        "{tool} description must contain {needle:?}; got:\n{haystack}"
    );
}

#[test]
fn get_callers_description_documents_callchain_field_semantics() {
    let d = description_of("get_callers");
    assert_contains(&d, "CALL site", "get_callers");
    assert_contains(&d, "DEFINITION site", "get_callers");
    assert_contains(&d, "depth ≥ 2", "get_callers");
}

#[test]
fn get_callees_description_documents_callchain_field_semantics() {
    let d = description_of("get_callees");
    assert_contains(&d, "CALL site", "get_callees");
    assert_contains(&d, "DEFINITION site", "get_callees");
    assert_contains(&d, "depth ≥ 2", "get_callees");
}

#[test]
fn get_callers_description_documents_resolved_only_filter() {
    let d = description_of("get_callers");
    assert_contains(&d, "Resolved-only filter", "get_callers");
    assert_contains(&d, "generate_diagram", "get_callers");
}

#[test]
fn get_callees_description_documents_resolved_only_filter() {
    let d = description_of("get_callees");
    assert_contains(&d, "Resolved-only filter", "get_callees");
    assert_contains(&d, "generate_diagram", "get_callees");
}

#[test]
fn get_callers_description_documents_non_callable_soft_hint() {
    let d = description_of("get_callers");
    assert_contains(&d, "Non-callable soft-hint", "get_callers");
    // Each non-callable kind name + the routed alternative tools.
    for kind in ["struct", "enum", "trait", "typedef", "interface"] {
        assert_contains(&d, kind, "get_callers");
    }
    assert_contains(&d, "get_class_hierarchy", "get_callers");
    assert_contains(&d, "get_symbol_detail", "get_callers");
}

#[test]
fn get_callees_description_documents_non_callable_soft_hint() {
    let d = description_of("get_callees");
    assert_contains(&d, "Non-callable soft-hint", "get_callees");
    for kind in ["struct", "enum", "trait", "typedef", "interface"] {
        assert_contains(&d, kind, "get_callees");
    }
    assert_contains(&d, "get_class_hierarchy", "get_callees");
    assert_contains(&d, "get_symbol_detail", "get_callees");
}

#[test]
fn search_symbols_description_documents_suggestions_field() {
    let d = description_of("search_symbols");
    assert_contains(&d, "suggestions", "search_symbols");
    // Anchored `^…$` trigger condition + zero-match precondition.
    assert_contains(&d, "^…$", "search_symbols");
    assert_contains(&d, "total == 0", "search_symbols");
    // Absent-when-empty contract.
    assert_contains(
        &d,
        "Absent from the wire entirely when empty",
        "search_symbols",
    );
    // `count_only` exclusion.
    assert_contains(&d, "Never emitted on `count_only=true`", "search_symbols");
}
